apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: analytics

bases:
  - ../../base

images:
  - name: tinybirdco/tinybird-local
    newTag: latest
  - name: ghost/traffic-analytics
    newTag: latest

patchesStrategicMerge:
  - resource-limits.yaml
