apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: analytics

resources:
  - namespace.yaml
  - tinybird-pvc.yaml
  - tinybird-deployment.yaml
  - tinybird-service.yaml
  - traffic-analytics-deployment.yaml
  - traffic-analytics-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: tinybird-analytics
